---
title: "R Notebook"
output: html_notebook
---
```{r}
library("nnet")
library("e1071")
require(XLConnect)
library("randomForest")
library("dplyr")
library("caret")
library("writexl")
library("neuralnet")
library(caTools)
library("ROSE")
library("ROCR")
library("DMwR")
library("xgboost")

print("Loaded Packages")


```


```{r}
print("Loading data")
wb = loadWorkbook("ra.xlsx")
df = readWorksheet(wb, sheet = "Training Dataset", header = TRUE)
print("Data set Loaded...")
#s_df <-  sample(1:nrow(df))
#df <- df[s_df, ]  #manual shuffling code
#head(df)
```


```{r}
dim(df)  # checking dimesions
```


```{r}
df1 = df %>% mutate_if(is.character, as.factor) # changing character to as a factor
df1$Treatment <- as.factor(df1$Treatment)
table(df1$Treatment)
#Changing range values to single digit
new_df <- mutate(df1, Age=ifelse(Age =="0-19",0 ,Age),
                 Age=ifelse(Age =="20-29",1,Age),Age=ifelse(Age =="30-39",2 ,Age),
                 Age=ifelse(Age =="40-49",3,Age),Age=ifelse(Age =="50-59",4 ,Age),
                 Age=ifelse(Age =="60-69",5,Age),Age=ifelse(Age =="70-79",6 ,Age),
                 Age=ifelse(Age ==">=80",7,Age))

dim(new_df)

#sapply( new_df, function(x) sum(is.na(x))) #to check null value counts in each column

#str(new_df)
```


```{r}
library("ggplot2")
library("naniar")

gg_miss_var(new_df)


```


```{r}

getmode <- function(v) {
   v1 <- na.omit(v) # removing NA 
   uniqv <- unique(v1)
   uniqv[which.max(tabulate(match(v1, uniqv)))]
}


for(i in 2:ncol(new_df)){
  
  if(length(unique(new_df[,i]))  == 3){
    
      
      fff = getmode(new_df[,i]) # get mode of the column
      
      new_df[is.na(new_df[,i]), i] <- fff
    
  }else {
    
    new_df[is.na(new_df[,i]), i] <- round(median(new_df[,i], na.rm = TRUE)) # replacing with mean of column
    
  }
  
  
}

#str(new_df)
#sapply( new_df, function(x) sum(is.na(x)))

write_xlsx(new_df,"E:\\stdies\\Data_Science\\q3\\datascience\\project\\Referral_Advice\\new_RA.xlsx")
```


```{r}


#Visualization of data set labels

one_Value = filter(new_df,new_df$Treatment == 1)
two_Value = filter(new_df,new_df$Treatment == 2)
three_Value = filter(new_df,new_df$Treatment == 3)
four_Value = filter(new_df,new_df$Treatment == 4)
five_Value = filter(new_df,new_df$Treatment == 5)

H <- c(length(one_Value$Treatment),length(two_Value$Treatment),length(three_Value$Treatment)
       ,length(four_Value$Treatment),length(five_Value$Treatment))

M <- c("Advice","Rehab","surgery","inj/med","comb 1-4")

barplot.default(H,names.arg=M,xlab="Labels",ylab="Counts",col="blue",main="LBP Data Volumes",border="red")


pie(table(new_df$Treatment))
```


```{r}

H <- c(658, 450, 522, 600, 640)
       
M <- c("Advice","Rehab","surgery","inj/med","comb 1-4")

barplot.default(H,names.arg=M,xlab="Labels",ylab="Counts",col="blue",ylim=c(0,1000) , main="LBP Data Volumes",border="red")


```


```{r}
tab <- table(new_df$Treatment)
tab
prop.table(tab)

#data_over <- ovun.sample(Treatment~., data = train1, method = "over", N=nrow(train1))$data
set.seed(123)
data_over <- SMOTE(Treatment~.,new_df,perc.over = 6000)

table(data_over$Treatment)
prop.table(table(data_over$Treatment))

```


```{r}
# SEPARATING TEST AND TRAINING SET - FOR DT, LR, RF models

library(caTools)
set.seed(222)
sample = sample.split(new_df,SplitRatio = 0.70)
train1 =subset(new_df,sample ==TRUE)
test1=subset(new_df, sample==FALSE)

# PLOTTING GRAPH FOR TRAINING SET

one_Value_tr = filter(train1,train1$Treatment == 1)
two_Value_tr = filter(train1,train1$Treatment == 2)
three_Value_tr = filter(train1,train1$Treatment == 3)
four_Value_tr = filter(train1,train1$Treatment == 4)
five_Value_tr = filter(train1,train1$Treatment == 5)


length(one_Value_tr$Treatment)
length(two_Value_tr$Treatment)
length(three_Value_tr$Treatment)
length(four_Value_tr$Treatment)
length(five_Value_tr$Treatment)
print("----------------------")
H <- c(length(one_Value_tr$Treatment),length(two_Value_tr$Treatment),length(three_Value_tr$Treatment)
       ,length(four_Value_tr$Treatment),length(five_Value_tr$Treatment))

M <- c("Advice","Rehab","surgery","inj/med","comb 1-4")

barplot.default(H,names.arg=M,xlab="Labels",ylab="Counts",col="blue",ylim=c(0,1000),main="LBP training Data Volumes",border="red")
pie(table(H))

# PLOTTING GRAPH FOR TEST SET

one_Value_te = filter(test1,test1$Treatment == 1)
two_Value_te = filter(test1,test1$Treatment == 2)
three_Value_te = filter(test1,test1$Treatment == 3)
four_Value_te = filter(test1,test1$Treatment == 4)
five_Value_te = filter(test1,test1$Treatment == 5)

length(one_Value_te$Treatment)
length(two_Value_te$Treatment)
length(three_Value_te$Treatment)
length(four_Value_te$Treatment)
length(five_Value_te$Treatment)

H <- c(length(one_Value_te$Treatment),length(two_Value_te$Treatment),length(three_Value_te$Treatment)
       ,length(four_Value_te$Treatment),length(five_Value_te$Treatment))

M <- c("Advice","Rehab","surgery","inj/med","comb 1-4")

barplot.default(H,names.arg=M,xlab="Labels",ylab="Counts",col="blue",ylim=c(0,1000),main="LBP test Data Volumes",border="red")
```


```{r}

tab <- table(train1$Treatment)
tab
prop.table(tab)

#data_over <- ovun.sample(Treatment~., data = train1, method = "over", N=nrow(train1))$data
set.seed(123)
data_over <- SMOTE(Treatment~ .,train1,perc.over = 9000)

table(data_over$Treatment)
prop.table(table(data_over$Treatment))


```




```{r}

# DECISION TREE

#Duration_of_pain+Earlier_hospitalization+Familiy_history+Kinesiophobia_physical_exercise+Kinesiophobia_pain_stop+Age+Uses_analgesics+Uses_corticosteroids+Serious_disease+Neurogenic_signals+Continuous_pain+Decreased_mobility+Nocturnal_pain+low_back_pain_intensity+Paidwork

#Duration_of_pain+Earlier_hospitalization+Familiy_history+Irrational_thoughts_risk_lasting+Kinesiophobia_physical_exercise+Kinesiophobia_pain_stop+Age+Uses_analgesics+Uses_corticosteroids+Serious_disease+Neurogenic_signals+Continuous_pain+Decreased_mobility+Nocturnal_pain+neck_pain_intensity+low_back_pain_intensity+arm_left_pain_intensity+arm_right_pain_intensity+leg_left_pain_intensity+leg_right_pain_intensity

library(rpart)
library(rpart.plot)

decision <- rpart(Treatment~ Continuous_pain+Uses_analgesics+Serious_disease+Fever+Trauma+Duration_of_pain+Irrational_thoughts_work+Age+Kinesiophobia_physical_exercise+Uses_corticosteroids+Paidwork+leg_left_pain_intensity+low_back_pain_intensity+Nocturnal_pain+Stress+ Depression+ Sick_leave+Loss_muscle_strength , data = data_over, method = "class", 
control = rpart.control(minsplit =6, minbucket = round(5/3) ,maxdepth = 8, cp =0))
rpart.plot(decision,extra = 100)
```


```{r}
pre_Train = predict(decision, data_over, type = "class")
#print(pre)
#print(test1$Treatment)
table(pre)
table(data_over$Treatment)

u <- union(pre_Train, data_over$Treatment)
t <- table(factor(pre_Train, u), factor(data_over$Treatment, u))
confusionMatrix(t)
```


```{r}
#head(pre)

pre = predict(decision, test1, type = "class")

#print(pre)
#print(test1$Treatment)

table(pre)
table(test1$Treatment)
u <- union(pre, test1$Treatment)
t <- table(factor(pre, u), factor(test1$Treatment, u))
confusionMatrix(t)



```


```{r}

```


```{r}
#Logistic Regression

log_Reg = multinom(formula = Treatment~., data = train1)
#summary(log_Reg)
```


```{r}
pre_train_mlr = predict(log_Reg, train1, type = "class")
u <- union(pre_train_mlr, train1$Treatment)
t <- table(factor(pre_train_mlr, u), factor(train1$Treatment, u))
confusionMatrix(t)

```


```{r}
pre_test_mlr = predict(log_Reg, test1, type = "class")
#print(pre)
#print(test1$Treatment)

#table(pre)
#table(test1$Treatment)
u <- union(pre_test_mlr, test1$Treatment)
t <- table(factor(pre_test_mlr, u), factor(test1$Treatment, u))
confusionMatrix(t)
```


```{r}
```


```{r}
```


```{r}

rf <- randomForest(formula = Treatment ~ ., data = train1 ,importance=TRUE)

print(rf)
plot(rf, )

t <- tuneRF(train1[,-1],train1[,1],stepFactor = 0.5, plot=TRUE, ntreeTry = 300, trace = TRUE,
          improve = 0.05)
t

varImpPlot(rf)

```


```{r}
pre_train_mrf = predict(rf, train1, type = "class")

table(pre_train_mrf)
table(train1$Treatment)

u <- union(pre_train_mrf, train1$Treatment)
t <- table(factor(pre_train_mrf, u), factor(train1$Treatment, u))
confusionMatrix(t)



```


```{r}
pre_train_mrf = predict(rf, test1, type = "class")
#print(pre)
#print(test1$Treatment)

table(pre_train_mrf)
table(test1$Treatment)
u <- union(pre_train_mrf, test1$Treatment)
t <- table(factor(pre_train_mrf, u), factor(test1$Treatment, u))
confusionMatrix(t)
```


```{r}
#Neural Network
DF_NN = data_over
DF_NN$Treatment <- as.numeric(as.character(DF_NN$Treatment))
#sapply( DF_NN, as.numeric )
#str(DF_NN)

#Normalising the data for NN

for(i in 1:ncol(DF_NN)){
  DF_NN[,i] <- (DF_NN[,i]-min(DF_NN[,i]))/(max(DF_NN[,i])-min(DF_NN[,i]))
}
```


```{r}
#sampleNN = sample.split(DF_NN,SplitRatio = 0.70)

sampleNN = sample.split(DF_NN,SplitRatio = 0.70)
trainNN =subset(DF_NN,sample ==TRUE)
testNN=subset(DF_NN, sample==FALSE)

#sampleNN = sample(1:nrow(DF_NN),1600)
#head(DF_NN[sampleNN,])

#trainNN =subset(DF_NN,sample ==TRUE)
#testNN=subset(DF_NN, sample==FALSE)

#trainNN = DF_NN[sampleNN,]


#testNN= DF_NN[-sampleNN,]
#str(trainNN)

prop.table(table(trainNN$Treatment))
prop.table(table(testNN$Treatment))


```


```{r}
NN <- neuralnet(Treatment ~ Fever + Duration_of_pain + Irrational_thoughts_work +   Kinesiophobia_physical_exercise + Age + Uses_analgesics +  Serious_disease + Continuous_pain + Trauma + Paidwork, data = trainNN, hidden = c(4), linear.output = FALSE)
plot(NN)
```


```{r}

output <- compute(NN, testNN[,-1])
predNN <- output$net.result * (max(DF_NN[-sampleNN,37])- min(DF_NN[-sampleNN,37])) + min(DF_NN[-sampleNN,37])


actualNN <- DF_NN[-sampleNN,37]

predNN2 <- ifelse(predNN>0.5,1,0)
#print(predNN)

#MSE <- sum((predNN - actualNN )^2)/nrow(testNN)
#MSE
#table(actualNN,round(predNN))


tab <- table(predNN2,testNN$Treatment)
tab

u <- union(round(predNN),testNN$Treatment)
t <- table(factor(round(predNN), u), factor(testNN$Treatment, u))
confusionMatrix(t)



```

